Repository apa-developer/apa-ui, pull requests merged in 2024-12, with the labels that each got.

#19 import cn
  components/react-ts/button.tsx
  components/react/button.jsx
Labels: Utils

#25 Add GitHub Actions workflow for linting on pull requests and update lint script
  .github/workflow/main-on-pr.yml
  bun.lockb
  components/react-ts/button.tsx
  eslint.config.mjs
  package.json
  tsconfig.json
Labels: Button, dependencies

#28 Move dependencies to devDependencies and integrate Prettier plugin
  .github/workflows/main-on-pr.yml
  .prettierrc
  bun.lockb
  components/react-ts/button.tsx
  components/react-ts/input.tsx
  components/react/button.jsx
  eslint.config.mjs
  package.json
Labels: dependencies

#29 Improve GitHub Actions workflow for dependencies and linting
  .github/workflows/main-on-pr.yml
  bun.lockb
Labels: enhancement

#33 chore: create codeowners
  .github/CODEOWNERS
Labels: ready-to-merge

#35 ci(Mergify): configuration update
  .mergify.yml
Labels: ready-to-merge

#36 chore: setup commit lint & fix eslint hangs
  .github/workflows/commitlint.yml
  .husky/commit-msg
  .husky/pre-commit
  .mergify.yml
  bun.lockb
  commitlint.config.js
  eslint.config.mjs
  package.json
Labels: ready-to-merge, JavaScript

#38 chore: rename pm script to npm
  package.json
Labels: ready-to-merge, CI/CD

#41 fix: Add Node.js setup step to GitHub Actions workflow for branch builds
  .github/workflows/branches-on-push.yml
Labels: CI/CD

#42 ci: Add release configuration for semantic-release
  release.config.mjs
Labels: CI/CD

#43 fix: Update release configuration to use 'main' branch
  release.config.mjs
Labels: CI/CD

#44 ci: update GitHub Actions workflow to add permissions for release publishing and issue commenting
  .github/workflows/branches-on-push.yml
Labels: CI/CD

#45 refactor: rename build job to release and update token variable in workflow
  .github/workflows/branches-on-push.yml
Labels: CI/CD

#52 Remove `version` prop from `package.json`
  bun.lockb
  package.json
Labels: documentation

#54 build: update release workflow to copy necessary files before semantic release
  .github/workflows/branches-on-push.yml
Labels: CI/CD

#55 ci: remove unnecessary newline in branches-on-push workflow
  .github/workflows/branches-on-push.yml
Labels: CI/CD

#56 build: streamline semantic release command in branches-on-push workflow
  .github/workflows/branches-on-push.yml
Labels: CI/CD

#57 docs: update documentation and package metadata
  README.md
  package.json
  release.config.mjs
Labels: documentation

#61 feat: checkbox with refactor another component
  components/react-ts/checkbox.tsx
  components/react-ts/input.tsx
  components/react/button.jsx
  components/react/checkbox.jsx
  components/react/input.jsx
Labels: React

#63 ci: remove unnecessary files from release workflow and delete redundant main branch workflow
  .github/workflows/branches-on-push.yml
  .github/workflows/main-on-push.yml
Labels: enhancement, CI/CD

#64 ci: using `.gitignore` instead remove dev files in workflow
  .github/workflows/branches-on-push.yml
  .npmignore
Labels: CI/CD

#65 fix: lint error
  .github/workflows/branches-on-push.yml
  components/react-ts/button.tsx
  components/react-ts/checkbox.tsx
  components/react-ts/input.tsx
  components/react-ts/radio.tsx
  components/react-ts/textarea.tsx
  components/react/button.jsx
  components/react/checkbox.jsx
  components/react/input.jsx
  components/react/radio.jsx
  components/react/textarea.jsx
Labels: Button, Radio, Checkbox, Input, Textarea, Select, React, CI/CD

#66 ci: add commitlint validation for PRs and last commit, remove old workflow
  .github/workflows/branches-on-pr.yml
  .github/workflows/branches-on-push.yml
  .github/workflows/commitlint.yml
Labels: CI/CD

#69 docs: create usage documentation
  README.md
Labels: documentation, ready-to-merge

#73 feat(react): add 'select' component
  components/react-ts/select.tsx
  package-lock.json
  package.json
Labels: React

#78 fix: init command not copied utils files
  .gitignore
  bun.lockb
  package-lock.json
  package.json
  src/commands/init.ts
Labels: TypeScript, COMMANDS
